from __future__ import annotations


def ref(title: str, creator: str, meta: str, note_zh: str, note_en: str) -> dict:
    return {
        "title": title,
        "creator": creator,
        "meta": meta,
        "note_zh": note_zh,
        "note_en": note_en,
    }


def profile(
    question_en: str,
    throughline: str,
    concept_frame: str,
    judgment_frame: str,
    case_frame: str,
    toolkit_frame: str,
    values_frame: str,
    system_frame: str,
    integration_frame: str,
) -> dict:
    return {
        "question_en": question_en,
        "throughline": throughline,
        "concept_frame": concept_frame,
        "judgment_frame": judgment_frame,
        "case_frame": case_frame,
        "toolkit_frame": toolkit_frame,
        "values_frame": values_frame,
        "system_frame": system_frame,
        "integration_frame": integration_frame,
    }


PRIORITY_THINKER_IDS = [
    "buffett",
    "charlie_munger",
    "steve_jobs",
    "sam_altman",
    "alan_turing",
    "albert_einstein",
    "confucius",
    "laozi",
    "lee_kuan_yew",
    "zhongnanshan",
    "peter_drucker",
    "peter_thiel",
    "ray_dalio",
    "bezos",
    "satya_nadella",
    "andrew_ng",
    "li_feifei",
    "daniel_kahneman",
    "aristotle",
    "socrates",
    "wang_yangming",
    "linus_torvalds",
    "tim_berners_lee",
    "musk",
    "caodewang",
    "zaha_hadid",
]


CURATED_PILLAR_GLOSSES = {
    "buffett": ["value investing", "compounding", "moats"],
    "charlie_munger": ["inversion", "mental models", "cognitive bias"],
    "steve_jobs": ["product taste", "aesthetic judgment", "end-to-end experience"],
    "sam_altman": ["AGI", "startups", "distribution"],
    "alan_turing": ["computation", "formalization", "machine intelligence"],
    "albert_einstein": ["first principles", "imagination", "unification"],
    "confucius": ["ren (humaneness)", "li (ritual order)", "self-cultivation"],
    "laozi": ["non-coercive action", "softness over force", "alignment with the dao"],
    "lee_kuan_yew": ["governance", "talent", "long-term statecraft"],
    "zhongnanshan": ["evidence", "public health", "plain speaking"],
    "peter_drucker": ["management", "knowledge work", "mission"],
    "peter_thiel": ["monopoly", "contrarian truth", "zero-to-one thinking"],
    "ray_dalio": ["principles", "transparency", "systems decision-making"],
    "bezos": ["customer obsession", "Day 1", "flywheel systems"],
    "satya_nadella": ["empathy", "platform renewal", "learning culture"],
    "andrew_ng": ["AI democratization", "applied AI", "learning loops"],
    "li_feifei": ["human-centered AI", "vision intelligence", "education"],
    "daniel_kahneman": ["System 1 / System 2", "bias", "judgment under uncertainty"],
    "aristotle": ["virtue", "the mean", "practical wisdom"],
    "socrates": ["questioning", "virtue", "self-examination"],
    "wang_yangming": ["unity of knowing and doing", "innate knowing", "self-examination"],
    "linus_torvalds": ["open source", "engineering aesthetics", "direct feedback"],
    "tim_berners_lee": ["open web", "standards", "public infrastructure"],
    "musk": ["first principles", "manufacturing", "frontier ambition"],
    "caodewang": ["manufacturing", "pragmatism", "craft discipline"],
    "zaha_hadid": ["form", "spatial flow", "structural daring"],
}


CURATED_ENGLISH_PROFILES = {
    "buffett": profile(
        "Where is the durable economic reality, and what would have to stay true for it to keep compounding?",
        "Buffett reads the world through business quality, time horizon, and capital discipline rather than price motion.",
        "In Buffett's vocabulary, {concept} is not a slogan. It is a filter for separating durable economics from temporary excitement.",
        "His judgment order is slow on purpose: understand the business, protect the downside, price the bet, and only then act.",
        "The cases matter because Buffett's edge rarely came from speed. It came from refusing to leave his circle of competence.",
        "The toolkit is concrete: circle of competence, margin of safety, owner earnings, opportunity cost, and disciplined inactivity.",
        "Under the mechanics sits a moral style: patience, candor about limits, and respect for reality over market theater.",
        "To operationalize Buffett, you need a watchlist, a business-quality filter, and a rule against forced activity.",
        "The end state is not to sound like Buffett. It is to make calmer, better-priced decisions when markets or teams get noisy.",
    ),
    "charlie_munger": profile(
        "What would this look like if I inverted the problem and checked it from multiple mental models first?",
        "Munger is best read as a builder of judgment through inversion, multidisciplinary models, and brutal clarity about error.",
        "For Munger, {concept} is useful only when it helps you avoid stupidity before chasing brilliance.",
        "He judges by clearing the obvious errors first, then testing the decision against psychology, incentives, and second-order effects.",
        "The cases matter because Munger's best lessons usually come from watching where human misjudgment quietly compounds.",
        "His toolkit is a latticework: inversion, incentives, margin of safety, base rates, and a permanent allergy to self-deception.",
        "The moral center is stronger than people notice: earn trust, deserve what you want, and keep your reasoning clean.",
        "Operational Munger means building checklists against avoidable stupidity before building plans for upside.",
        "You are not trying to mimic his voice. You are trying to become harder to fool, especially by yourself.",
    ),
    "steve_jobs": profile(
        "What is the simplest end-to-end experience worth obsessing over, and what should be removed to protect it?",
        "Jobs works as a system of product taste, ruthless focus, and end-to-end control over the user experience.",
        "With Jobs, {concept} is never decoration. It is a decision about what deserves attention and what must disappear.",
        "His judgment sequence starts with the desired user experience, then backs into technology, team structure, and trade-offs.",
        "The cases matter because Jobs used launches and redesigns to prove that subtraction can be a strategic weapon.",
        "The toolkit is not generic creativity. It is taste, narrative compression, sequencing, and the discipline to say no repeatedly.",
        "Beneath the charisma is a severe value system: craftsmanship matters, details teach culture, and mediocre work poisons the whole.",
        "To operationalize Jobs, define the experience first, reduce the number of priorities, and force every team to serve the same story.",
        "The real takeaway is not theatrical perfectionism. It is learning how design discipline changes the quality of decisions.",
    ),
    "sam_altman": profile(
        "Which constraint is truly limiting scale right now, and what gets dramatically better if the system compounds from here?",
        "Altman thinks in systems: talent density, product distribution, compute, and long-run compounding all reinforce one another.",
        "For Altman, {concept} is only meaningful when it compounds through users, infrastructure, and distribution at the same time.",
        "He judges quickly but not casually: identify the bottleneck, remove historical baggage, and place the bet where scale changes everything.",
        "The cases matter because Altman's style becomes visible when he turns future possibility into near-term operating choices.",
        "His toolkit is built for builders: first-principles reframing, founder speed, talent concentration, product iteration, and platform leverage.",
        "The underlying values are unusually clear: optimism, ambition, and a bias toward building systems large enough to matter.",
        "To run Altman as an operating model, keep a bottleneck map, accelerate feedback loops, and track where scale begins to bend outcomes.",
        "You should come away less impressed by rhetoric and more fluent in how compounding systems are actually built.",
    ),
    "alan_turing": profile(
        "What part of this problem can be made precise enough to compute, and what remains outside the model?",
        "Turing is a thinker of formal limits: he clarifies what can be computed, simulated, or inferred before mythology takes over.",
        "With Turing, {concept} becomes a test of whether the problem can be represented rigorously enough to be worked on at all.",
        "His judgment starts with formalization: define the symbols, define the process, and be honest about the boundary of the model.",
        "The cases matter because Turing's breakthroughs came from turning philosophical confusion into technical structure.",
        "The toolkit is formal but practical: abstraction, reduction, simulation, and the courage to ask whether the machine model is the right one.",
        "His value system combines imagination with rigor: bold hypotheses are welcome, but only after the machinery is made explicit.",
        "Operational Turing means forcing ambiguous problems into clean representations and documenting what the representation leaves out.",
        "The course should leave you more precise, not merely more impressed by the origin story of computing.",
    ),
    "albert_einstein": profile(
        "Which assumption have we accepted as normal that should be re-examined from first principles?",
        "Einstein thinks by stripping a problem to its deepest invariants and then asking what must stay true in every frame.",
        "For Einstein, {concept} matters because it exposes the hidden assumption underneath the familiar picture of reality.",
        "His judgment does not begin with complexity. It begins by simplifying the frame until the contradiction becomes visible.",
        "The cases matter because Einstein's big moves came from re-reading ordinary concepts like time, motion, and observation.",
        "His toolkit is conceptual: thought experiments, symmetry, invariance, and the refusal to accept inherited categories too quickly.",
        "The values beneath the science are intellectual honesty, simplicity, and a willingness to stand apart from consensus.",
        "To operationalize Einstein, isolate the invariant, re-state the problem in cleaner terms, and challenge the background assumption.",
        "The real gain is not pseudo-genius theater. It is learning to clean the frame before multiplying details.",
    ),
    "confucius": profile(
        "What kind of person, relationship, and order does this decision create if repeated over time?",
        "Confucius should be read as a system of moral cultivation, relational order, and disciplined self-correction.",
        "In Confucius, {concept} is not abstract virtue talk. It is a practical way of shaping conduct, role, and trust over time.",
        "His judgment asks about the person and the relationship before the tactic: what role is being performed, and with what integrity?",
        "The cases matter because Confucian teaching lives in ordinary conduct, not in detached theory alone.",
        "The toolkit is relational: self-examination, role clarity, ritual discipline, naming things correctly, and learning through practice.",
        "The value system is explicit: humanity, appropriateness, reciprocity, and the long work of becoming trustworthy.",
        "Operational Confucius means turning principles into repeated habits of speech, conduct, attention, and correction.",
        "The point is not reverence for tradition. It is learning how character and order are built through repeated practice.",
    ),
    "laozi": profile(
        "Where is force creating fragility, and what changes if we work with the grain of the situation instead?",
        "Laozi is best approached as a thinker of alignment, restraint, and power that comes from not over-managing the world.",
        "For Laozi, {concept} is a way of noticing when effort is producing friction instead of harmony.",
        "His judgment begins by reducing force: stop overdesigning the intervention and ask what the situation is already trying to become.",
        "The cases matter because Daoist wisdom shows itself when over-control fails and strategic restraint wins.",
        "The toolkit is subtle: reversal, emptiness, non-coercion, softness, and attention to the direction of the whole system.",
        "The values are disciplined rather than passive: humility, non-display, proportion, and distrust of domination.",
        "Operational Laozi means reducing unnecessary control points, preserving room, and timing action to the shape of the environment.",
        "The real transfer is not mystical language. It is learning when less intervention produces better order.",
    ),
    "lee_kuan_yew": profile(
        "What institutional choice increases state capacity over the next generation rather than only solving today's headline?",
        "Lee Kuan Yew thinks in institutions, incentives, talent, and long time horizons rather than slogans or symbolic gestures.",
        "In Lee's framework, {concept} matters only if it can survive contact with administration, incentives, and social order.",
        "He judges like a state builder: define the strategic constraint, align the institution, and then insist on execution quality.",
        "The cases matter because Lee's governance logic only makes sense when you see policy, personnel, and discipline move together.",
        "The toolkit is institutional: talent selection, incentive design, clean administration, strategic sequencing, and refusal of sentimentality.",
        "The value system is stern but coherent: order before drift, competence before theater, and long-term legitimacy through results.",
        "Operational Lee means translating ideals into institutions, incentives, and measurable administrative behavior.",
        "The transfer is not authoritarian imitation. It is learning how durable governance is built through hard institutional choices.",
    ),
    "zhongnanshan": profile(
        "What does the evidence actually support right now, and what must be said clearly before the situation worsens?",
        "Zhong Nanshan is best read through evidence discipline, public responsibility, and clinical realism under pressure.",
        "For Zhong, {concept} becomes meaningful only when it changes diagnosis, treatment, prevention, or public communication.",
        "His judgment begins with evidence quality, then risk severity, then the duty to communicate plainly despite uncertainty.",
        "The cases matter because clinical and public-health decisions reveal whether someone protects truth when pressure rises.",
        "The toolkit is practical medicine: evidence grading, triage, crisis communication, team coordination, and fast feedback from the frontline.",
        "The value system is straightforward: tell the truth, respect evidence, and put prevention and public safety ahead of face-saving.",
        "Operational Zhong means linking data, bedside reality, and public messaging into one decision loop.",
        "The real lesson is not reputation. It is learning how evidence-based judgment behaves under public pressure.",
    ),
    "peter_drucker": profile(
        "What is the mission here, who is the customer, and what result actually counts as performance?",
        "Drucker is a system thinker of mission, management, and knowledge work, not a pile of productivity slogans.",
        "For Drucker, {concept} only matters when it helps an organization produce contribution, not motion for its own sake.",
        "He judges by mission first, then by what the organization is uniquely there to do, and only then by structure or metrics.",
        "The cases matter because Drucker's ideas become sharp when management choices either clarify contribution or bury it.",
        "His toolkit is managerial but human: mission discipline, contribution focus, knowledge-worker design, and management by objectives.",
        "His values are quietly radical: respect people as contributors, define purpose clearly, and make results discussable.",
        "Operational Drucker means turning strategy into mission, responsibilities, decisions, and review loops that ordinary teams can use.",
        "The course should leave you with cleaner management questions, not more management vocabulary.",
    ),
    "peter_thiel": profile(
        "What important truth is still undervalued here, and what monopoly-quality advantage could be built from it?",
        "Thiel is best read as a strategist of contrarian truth, technological leverage, and asymmetric company building.",
        "With Thiel, {concept} matters because it changes whether you are building something scarce or merely competing harder in the same lane.",
        "His judgment begins by rejecting false competition, then searching for a hidden advantage strong enough to become a category.",
        "The cases matter because Thiel's strongest arguments live in market structure, distribution asymmetry, and non-obvious timing.",
        "The toolkit is strategic: secrets, monopoly power, distribution, compounding technology, and clear thinking against consensus.",
        "The value system is less cynical than it sounds: originality matters, drift is expensive, and mediocre imitation wastes lives.",
        "Operational Thiel means forcing every plan to answer what non-consensus truth it depends on and why that truth can endure.",
        "The transfer is not provocation for its own sake. It is learning how to search for genuinely non-obvious advantage.",
    ),
    "ray_dalio": profile(
        "What machine is running here, and which cause-and-effect relationships matter more than my current emotion?",
        "Dalio turns decision-making into systems thinking: principles, feedback loops, and cause-effect models over personal impulse.",
        "For Dalio, {concept} is useful only when it helps you see the machine rather than your current narrative about the machine.",
        "He judges by mapping the system, naming the error, and asking what principle would prevent the same mistake next time.",
        "The cases matter because Dalio's work is most concrete when principles collide with markets, ego, and organizational reality.",
        "His toolkit is systematic: believability-weighted input, pain-plus-reflection, principles, loop diagrams, and radical transparency.",
        "The values are operational: truth, adaptation, and the willingness to let evidence embarrass the current self.",
        "Operational Dalio means writing principles down, turning mistakes into data, and reviewing the machine instead of defending identity.",
        "The goal is not to imitate Bridgewater culture wholesale. It is to think more clearly about cause, feedback, and error correction.",
    ),
    "bezos": profile(
        "What creates durable customer value here, and what would a genuine Day 1 decision look like?",
        "Bezos is a thinker of customer obsession, systems scale, and long-term operating courage.",
        "For Bezos, {concept} matters only if it improves the customer experience in a way that compounds through the flywheel.",
        "He judges by starting from the customer, then backing into infrastructure, incentives, and patience.",
        "The cases matter because Bezos repeatedly used memos, mechanisms, and product bets to make long-horizon thinking operational.",
        "The toolkit is managerial and architectural: working backwards, narrative memos, flywheels, high standards, and patient reinvestment.",
        "The value system is demanding: avoid Day 2 drift, respect the customer signal, and build mechanisms that outlast charismatic intention.",
        "Operational Bezos means defining the customer promise first and then building the process discipline to sustain it at scale.",
        "The real transfer is not founder mythology. It is learning how long-term customer logic becomes a repeatable operating system.",
    ),
    "satya_nadella": profile(
        "How do we create a learning system here instead of defending an identity that no longer fits the environment?",
        "Nadella is best read as a leader of cultural renewal, platform leverage, and empathy-linked execution.",
        "For Nadella, {concept} matters when it unlocks learning, platform relevance, and a broader field of collaboration.",
        "His judgment starts with culture and strategy together: what must the organization become in order to make the technical shift real?",
        "The cases matter because Nadella's strongest work appears where culture change and platform bets reinforce one another.",
        "The toolkit is modern leadership: growth mindset, platform thinking, ecosystem partnerships, and culture made visible through operating choices.",
        "The values are disciplined and humane: empathy is not softness, learning is not drift, and renewal requires deliberate structure.",
        "Operational Nadella means changing incentives, language, product focus, and review habits so the new culture can survive contact with reality.",
        "The gain is not corporate niceness. It is learning how renewal happens without losing execution sharpness.",
    ),
    "andrew_ng": profile(
        "Where is the narrow, high-value application of AI that can be deployed now instead of admired from a distance?",
        "Andrew Ng thinks like a translator between frontier technology and practical deployment.",
        "For Andrew Ng, {concept} matters when it helps move AI from abstract promise into a concrete workflow with data, feedback, and users.",
        "His judgment begins with the application: choose the right use case, define the data problem, and keep the scope realistic enough to ship.",
        "The cases matter because his strongest work sits at the boundary between education, tooling, and real adoption.",
        "The toolkit is pragmatic: small bets, data-centric iteration, workflow fit, educational clarity, and democratized access to capability.",
        "The values are constructive: make the field legible, lower the barrier to entry, and keep the work grounded in actual usefulness.",
        "Operational Andrew Ng means choosing a narrow use case, improving the data loop, and measuring whether the user workflow really changes.",
        "The end state is not generic AI enthusiasm. It is the ability to identify where applied intelligence creates real leverage.",
    ),
    "li_feifei": profile(
        "How do we expand technical capability without losing sight of the human being the system is supposed to serve?",
        "Fei-Fei Li works as a bridge between frontier AI, scientific imagination, and a human-centered moral frame.",
        "For Fei-Fei Li, {concept} matters when it deepens intelligence while keeping the human context visible rather than abstracted away.",
        "Her judgment starts with scientific ambition, but it stays grounded in data, human meaning, and the social responsibility of the field.",
        "The cases matter because Fei-Fei Li's work shows how technical platforms and human-centered framing can be built together.",
        "The toolkit is both scientific and civic: dataset construction, benchmarking, interdisciplinary translation, and public framing of AI's direction.",
        "The values are explicit: curiosity, inclusion, human dignity, and long-horizon stewardship of powerful technology.",
        "Operational Fei-Fei Li means pairing technical progress with design choices that preserve human context and social trust.",
        "The transfer is not just better AI vocabulary. It is learning how to keep scientific ambition aligned with human consequence.",
    ),
    "daniel_kahneman": profile(
        "Which part of this judgment is fast intuition, which part is slower analysis, and where is the bias most likely to enter?",
        "Kahneman is a cartographer of judgment error: he makes invisible cognitive shortcuts legible enough to correct.",
        "For Kahneman, {concept} becomes useful when it exposes a predictable bias instead of flattering your feeling of certainty.",
        "He judges by slowing the moment down: identify the heuristic, inspect the framing, and ask what the base rate is saying.",
        "The cases matter because Kahneman's work lives in ordinary errors that intelligent people make repeatedly and confidently.",
        "His toolkit is diagnostic: System 1 and System 2, base rates, prospect framing, noise, and pre-commitment against bias.",
        "The values are disciplined rather than inspirational: intellectual modesty, statistical sanity, and respect for how often judgment fails.",
        "Operational Kahneman means designing prompts, decisions, and review steps that reduce avoidable bias before it hardens into action.",
        "The point is not permanent hesitation. It is learning where confidence becomes expensive.",
    ),
    "aristotle": profile(
        "What kind of excellence is this practice training, and what would wise action look like in this specific situation?",
        "Aristotle is a thinker of virtue, classification, and practical wisdom grounded in how human beings actually live.",
        "With Aristotle, {concept} matters because it shapes the kind of character and judgment repeated action is building.",
        "His judgment begins from purpose: what is this thing for, what kind of excellence fits it, and what does the mean require here?",
        "The cases matter because Aristotle's philosophy is never only abstract. It is tested in habit, politics, rhetoric, and concrete choice.",
        "The toolkit is classical but alive: causes, categories, habituation, telos, and phronesis in particular situations.",
        "The values are thick with realism: flourishing needs practice, virtue needs formation, and judgment needs context.",
        "Operational Aristotle means linking actions to purpose, habits to character, and specific choices to the right kind of excellence.",
        "The course should make Aristotle feel usable again, not like a museum of definitions.",
    ),
    "socrates": profile(
        "What do we think we know here, and what collapses once the definition is examined carefully?",
        "Socrates is best read as a discipline of questioning, moral seriousness, and intellectual humility under pressure.",
        "For Socrates, {concept} matters because it reveals whether the current definition can survive examination.",
        "His judgment does not rush to the answer. It interrogates the assumptions until a truer question emerges.",
        "The cases matter because Socratic thought is inseparable from dialogue, tension, and the discomfort of not knowing cleanly.",
        "The toolkit is dialogic: elenchus, definition testing, moral inquiry, and the willingness to let false certainty fall apart.",
        "The values are simple and severe: truth over vanity, examination over performance, and care of the soul over applause.",
        "Operational Socrates means asking better questions, exposing confused terms, and refusing to move forward on lazy definitions.",
        "The real transfer is not rhetorical cleverness. It is courage in the face of uncertainty and self-examination.",
    ),
    "wang_yangming": profile(
        "What do I already know is right, and where exactly is action failing to keep up with that knowledge?",
        "Wang Yangming is a thinker of moral insight, self-cultivation, and the unity of knowing and doing.",
        "For Wang Yangming, {concept} matters only when it closes the gap between inner clarity and lived action.",
        "His judgment turns inward before it turns outward: examine the mind, locate self-deception, and then act from clarified knowledge.",
        "The cases matter because Wang's philosophy was forged in administration, exile, military command, and inward discipline.",
        "The toolkit is moral and practical: introspection, sincerity, extension of innate knowing, and immediate correction through action.",
        "The values are uncompromising: conscience is real, self-deception is costly, and knowledge without practice is unfinished.",
        "Operational Wang Yangming means building routines of reflection that immediately convert into conduct rather than postponed ideals.",
        "The gain is not moral sloganizing. It is learning how to reduce the distance between conviction and behavior.",
    ),
    "linus_torvalds": profile(
        "Does the code work, does the architecture stay clean, and is the feedback loop honest enough to keep improving it?",
        "Torvalds is a builder of engineering systems: blunt feedback, architecture discipline, and proof through working code.",
        "For Linus, {concept} only matters if it survives the repository, the review, and the realities of maintenance.",
        "His judgment is unapologetically empirical: show the code, inspect the architecture, and let the implementation settle the argument.",
        "The cases matter because open-source governance reveals whether engineering values can survive scale and disagreement.",
        "The toolkit is hard-edged and useful: version control, modularity, review culture, maintainership, and fast technical honesty.",
        "The value system is direct: competence matters, talk is cheap, and maintainability outranks performative cleverness.",
        "Operational Linus means tightening the feedback loop between idea, code, review, and release until reality answers quickly.",
        "The transfer is not abrasive style. It is learning how engineering truth emerges through working systems and honest review.",
    ),
    "tim_berners_lee": profile(
        "What should remain open, linkable, and interoperable if this system is meant to scale beyond its first owner?",
        "Berners-Lee is a thinker of open standards, universal addressability, and infrastructure designed for shared use.",
        "For Tim Berners-Lee, {concept} matters because it decides whether a network becomes generative or closed.",
        "His judgment starts with interoperability: can this work across institutions, survive decentralization, and stay linkable over time?",
        "The cases matter because the web was not only a technical invention; it was a governance choice about openness.",
        "His toolkit is infrastructural: standards, identifiers, protocols, decentralization, and design that privileges general use over control.",
        "The values are civic and technical at once: openness, universality, permissionless innovation, and public responsibility.",
        "Operational Berners-Lee means protecting portability, common standards, and user agency even when enclosure is tempting.",
        "The real lesson is not nostalgia for the early web. It is how architecture decisions carry moral consequences at scale.",
    ),
    "musk": profile(
        "If we re-derived the problem from physics and economics, what would the impossible-looking version actually require?",
        "Musk is best read as a builder of hard-tech ambition through first principles, vertical integration, and tolerance for pain.",
        "For Musk, {concept} matters when it changes the cost curve or capability frontier rather than just improving presentation.",
        "His judgment begins by breaking the problem into physics, cost, and engineering constraints before accepting conventional limits.",
        "The cases matter because Musk's style only makes sense when the ambition is tied to manufacturing, iteration, and brutal execution.",
        "The toolkit is frontier-builder logic: first principles, vertical integration, aggressive iteration, mission narrative, and engineering compression.",
        "The values are intense and double-edged: urgency, scale ambition, and refusal to treat accepted constraints as sacred.",
        "Operational Musk means identifying the real bottleneck, compressing the feedback loop, and aligning the organization with a hard technical frontier.",
        "The transfer is not founder drama. It is learning when deep ambition is real and what price it demands in execution.",
    ),
    "caodewang": profile(
        "Where is the real product truth, and what must be built well before we talk about image, scale, or narrative?",
        "Cao Dewang is a thinker of manufacturing reality, product quality, and founder responsibility grounded in the shop floor.",
        "For Cao, {concept} matters only if it improves product truth, cost discipline, or long-run manufacturing capability.",
        "His judgment starts from the product and the factory rather than finance theater: what is being made, at what quality, and by what discipline?",
        "The cases matter because manufacturing wisdom becomes visible in quality control, capital restraint, and plant-level choices.",
        "The toolkit is grounded: product-first thinking, factory discipline, cost control, cross-border manufacturing judgment, and blunt accountability.",
        "The values are straightforward: do real work, respect the craft, and do not let vanity outrun capability.",
        "Operational Cao Dewang means building from product truth outward, not from story inward.",
        "The gain is not folksy toughness. It is learning how industrial judgment protects a business from hollow growth.",
    ),
    "zaha_hadid": profile(
        "What spatial logic is trying to emerge here, and what must change in form, flow, and structure to let it appear?",
        "Zaha Hadid is a thinker of spatial imagination, formal daring, and architectural systems that refuse static geometry.",
        "For Zaha, {concept} is not a decorative flourish. It is a spatial instruction about movement, force, and perception.",
        "Her judgment begins with the spatial idea, then tests whether structure, circulation, and material can sustain it.",
        "The cases matter because Zaha's projects show how visionary form survives only when construction logic catches up.",
        "The toolkit is architectural and visual: drawings as thought, fluid geometry, parametric iteration, sequencing of experience, and structural negotiation.",
        "The values are exacting: ambition in form, refusal of stale convention, and belief that the built world can feel more alive than habit allows.",
        "Operational Zaha means protecting the conceptual gesture while translating it into buildable systems and user movement.",
        "The transfer is not merely visual boldness. It is learning how formal imagination becomes an executable design language.",
    ),
}


REFERENCE_LIBRARY = {
    "buffett": {
        "intro_zh": "这一组先读一手经营记录，再读权威整理和传记。巴菲特最值得信的材料，不是金句，而是几十年持续公开的资本配置记录。",
        "intro_en": "Start with the operating record, then move to the best curated collections and biographies. Buffett makes the most sense through decades of capital-allocation evidence, not isolated quotes.",
        "primary_sources": [
            ref("Berkshire Hathaway Shareholder Letters", "Warren Buffett", "1977–present · Berkshire Hathaway", "理解巴菲特长期资本配置逻辑的一手材料。", "The clearest first-person record of Buffett's capital allocation logic over time."),
            ref("Berkshire Hathaway Owner's Manual", "Warren Buffett", "1996 and later updates", "把巴菲特最稳定的治理原则和股东关系原则讲得最直接。", "A compact statement of Buffett's governance principles and owner mindset."),
            ref("Berkshire Hathaway Annual Meeting Q&A", "Warren Buffett and Charlie Munger", "annual public archive", "适合看他如何在开放问答里暴露真实判断顺序。", "Useful for seeing how Buffett reasons in unscripted public dialogue."),
        ],
        "core_reading": [
            ref("The Essays of Warren Buffett: Lessons for Corporate America", "Warren Buffett and Lawrence A. Cunningham", "book", "把股东信按主题重组，是最好的系统入口之一。", "One of the best structured entrances because it reorganizes the letters by theme."),
            ref("The Snowball: Warren Buffett and the Business of Life", "Alice Schroeder", "biography", "用传记视角补足巴菲特的性格、关系和时代背景。", "Adds personality, relationships, and historical context to the public record."),
            ref("Tap Dancing to Work: Warren Buffett on Practically Everything, 1966–2013", "Carol J. Loomis", "collection", "适合补足不同年份采访与公开表达中的连续性。", "Good for tracing continuity across interviews, remarks, and public commentary."),
        ],
    },
    "charlie_munger": {
        "intro_zh": "芒格要先读演讲和讲话原文，再读整理书和二手阐释。不要先从“思维模型”标签开始，要先看他如何反复讲“少犯错”。",
        "intro_en": "Read the talks first, then the edited collections and biographies. Do not start with the label 'mental models' before seeing how often Munger is really teaching error-avoidance.",
        "primary_sources": [
            ref("Poor Charlie's Almanack", "Charles T. Munger, edited by Peter D. Kaufman", "talks and collected materials", "最接近芒格本人表达节奏和结构的一本书。", "The closest single-volume entrance to Munger's own cadence and reasoning."),
            ref("A Lesson on Elementary, Worldly Wisdom as It Relates to Investment Management & Business", "Charlie Munger", "speech", "多元模型框架的核心演讲。", "The essential speech on the latticework of mental models."),
            ref("The Psychology of Human Misjudgment", "Charlie Munger", "speech", "读芒格一定要回到这篇，认知偏误部分最集中。", "A foundational text if you want the clearest statement of Munger on cognitive error."),
        ],
        "core_reading": [
            ref("Damn Right! Behind the Scenes with Berkshire Hathaway Billionaire Charlie Munger", "Janet Lowe", "biography", "补足芒格的生平、职业脉络与投资实践。", "Useful for life history, career context, and investment practice."),
            ref("Seeking Wisdom: From Darwin to Munger", "Peter Bevelin", "interpretive book", "不是芒格原著，但很适合把他的跨学科框架转成可用清单。", "Not authored by Munger, but strong at turning his framework into usable judgment tools."),
            ref("Charlie Munger: The Complete Investor", "Tren Griffin", "interpretive book", "适合快速梳理芒格的投资原则与心理学框架。", "A concise map of Munger's investment principles and psychology-heavy worldview."),
        ],
    },
    "steve_jobs": {
        "intro_zh": "乔布斯要同时读产品发布、公开演讲和权威传记。只看传记会神化他，只看发布会会误以为他只会讲故事。",
        "intro_en": "With Jobs, pair launches and speeches with the best biographies. Biography alone mythologizes him; product theater alone makes him look like a storyteller instead of a system builder.",
        "primary_sources": [
            ref("Stanford Commencement Address", "Steve Jobs", "2005 speech", "理解乔布斯如何把人生叙事压成行动原则的最好入口。", "A compact entry into how Jobs turned biography into operating principles."),
            ref("iPhone Introduction Keynote", "Steve Jobs", "2007 product launch", "看他如何把产品、故事和取舍压成一个完整体验。", "Shows how product, narrative, and trade-offs were compressed into one experience."),
            ref("Make Something Wonderful", "Steve Jobs Archive", "archive collection", "最适合直接接触乔布斯原话、邮件、采访与时间线材料。", "One of the best ways to encounter Jobs through primary remarks, memos, and interviews."),
        ],
        "core_reading": [
            ref("Steve Jobs", "Walter Isaacson", "biography", "最完整的主流传记，但读时要和产品史互相校正。", "The standard biography, best read alongside the product record."),
            ref("Becoming Steve Jobs", "Brent Schlender and Rick Tetzeli", "biography", "更强调乔布斯后期的成熟与组织能力。", "Useful for a more mature portrait of Jobs as a leader and operator."),
            ref("Creative Selection", "Ken Kocienda", "inside account", "从产品团队内部看乔布斯如何做细节判断。", "An inside product account of how Jobs shaped details and decision quality."),
        ],
    },
    "sam_altman": {
        "intro_zh": "Altman 不是传统写书型人物，要先读他的公开文章、YC/OpenAI 讲话和长访谈。真正有价值的是他如何讨论规模、人才、分发和未来曲线。",
        "intro_en": "Altman is not primarily a book-writer. Start with essays, YC/OpenAI talks, and long-form interviews. The value is in how he links scale, talent, distribution, and future curves.",
        "primary_sources": [
            ref("How to Be Successful", "Sam Altman", "essay", "最像 Altman 方法论底稿的一篇短文。", "A compact essay that reads like Altman's operating doctrine."),
            ref("Moore's Law for Everything", "Sam Altman", "essay", "理解他如何把技术复利和社会分配放到同一张图里。", "A strong entry into how he thinks about technological abundance and distribution."),
            ref("The Intelligence Age", "Sam Altman", "essay", "看他如何把 AI 进步、产品普及和制度问题绑在一起。", "Useful for seeing how he binds AI progress, adoption, and policy questions together."),
        ],
        "core_reading": [
            ref("Startup Playbook", "Sam Altman", "essay collection", "早期创业判断、速度和产品直觉的高密度入口。", "Dense on early-stage company judgment, speed, and product intuition."),
            ref("How to Start a Startup", "Y Combinator / Stanford lecture series", "lecture archive", "虽不是 Altman 一人著作，但极能补足他的创业语境。", "Not authored by Altman alone, but excellent for the startup context around his thinking."),
            ref("OpenAI and Y Combinator Interviews", "Sam Altman", "long-form interviews", "适合补足文章里没有展开的现实取舍。", "Useful for the real trade-offs that essays often compress."),
        ],
    },
    "alan_turing": {
        "intro_zh": "图灵必须先读论文原文，再读解说书。否则很容易只记住“图灵测试”，却没真正理解他的形式化思路。",
        "intro_en": "Read Turing's papers before the explanatory books. Otherwise you end up with the label 'Turing test' without the deeper habit of formal reasoning.",
        "primary_sources": [
            ref("On Computable Numbers, with an Application to the Entscheidungsproblem", "Alan Turing", "1936 paper", "计算理论真正的起点。", "The foundational paper for computability theory."),
            ref("Computing Machinery and Intelligence", "Alan Turing", "1950 paper", "理解图灵如何把智能问题转成可讨论的形式。", "Shows how Turing reframed intelligence into a tractable public question."),
            ref("Intelligent Machinery", "Alan Turing", "1948 report", "适合看他更开放、更探索式的一面。", "Useful for the more exploratory side of Turing's machine thinking."),
        ],
        "core_reading": [
            ref("The Essential Turing", "edited by B. Jack Copeland", "collected volume", "最好的图灵原典与说明合集之一。", "One of the best curated volumes of Turing's core writings."),
            ref("Alan Turing: The Enigma", "Andrew Hodges", "biography", "图灵生平与科学工作的经典传记。", "The classic biography and historical account of Turing's work."),
            ref("The Annotated Turing", "Charles Petzold", "guided reading", "适合把 1936 论文真正读懂。", "Especially good if you want to truly understand the 1936 paper."),
        ],
    },
    "albert_einstein": {
        "intro_zh": "爱因斯坦要先回到论文和自写通俗书，再用传记和文集补背景。重点不是名言，而是他如何清理一个问题的坐标系。",
        "intro_en": "Start with the papers and Einstein's own explanatory writing, then add biography. The key is not the quotations; it is how he cleans up the frame of a problem.",
        "primary_sources": [
            ref("On the Electrodynamics of Moving Bodies", "Albert Einstein", "1905 paper", "狭义相对论的原始文本。", "The original paper on special relativity."),
            ref("Does the Inertia of a Body Depend Upon Its Energy Content?", "Albert Einstein", "1905 paper", "E=mc² 的原始来源之一。", "One of the primary sources behind E=mc²."),
            ref("Relativity: The Special and the General Theory", "Albert Einstein", "1916 book", "看爱因斯坦如何亲自把理论解释给非专业读者。", "Shows Einstein explaining the theory in his own public voice."),
        ],
        "core_reading": [
            ref("Ideas and Opinions", "Albert Einstein", "essays and reflections", "适合补足他的科学观、政治观与知识观。", "Useful for Einstein's reflections on science, politics, and intellectual life."),
            ref("The World As I See It", "Albert Einstein", "essays", "更短，更适合看他的价值排序。", "Shorter and especially useful for his moral and civic outlook."),
            ref("Einstein: His Life and Universe", "Walter Isaacson", "biography", "传记层面的完整补充。", "A strong full-scale biography for life and context."),
        ],
    },
    "confucius": {
        "intro_zh": "孔子必须先读《论语》，再读注疏和现代阐释。不要先从成功学式摘句入手。",
        "intro_en": "Start with the Analects, then read commentary and modern interpretation. Do not begin with decontextualized inspirational fragments.",
        "primary_sources": [
            ref("The Analects", "Confucian tradition", "primary text", "孔子最核心的一手材料。", "The central primary text for Confucius."),
            ref("The Great Learning", "Confucian canon", "classical text", "适合补足修身到治事的递进结构。", "Useful for the ladder from self-cultivation to public order."),
            ref("The Doctrine of the Mean", "Confucian canon", "classical text", "适合理解“中”的动态平衡而不是折中。", "Helpful for understanding the dynamic balance behind the idea of the mean."),
        ],
        "core_reading": [
            ref("The Analects", "translation by Edward Slingerland or another scholarly edition", "scholarly translation", "读孔子最好直接配学术译注版本。", "A scholarly translation is the best practical way to read Confucius closely."),
            ref("Thinking Through Confucius", "David L. Hall and Roger T. Ames", "interpretive book", "适合把孔子放回关系性世界观里理解。", "Strong on reading Confucius through a relational worldview."),
            ref("Confucius: And the World He Created", "Michael Schuman", "contextual biography", "适合快速补历史和后世影响。", "A readable entry for historical context and later influence."),
        ],
    },
    "laozi": {
        "intro_zh": "老子先读《道德经》本身，再看不同译本和出土文本差异。核心不是神秘，而是“顺势、减法、反转”这套结构。",
        "intro_en": "Read the Daodejing itself first, then compare translations and manuscript traditions. The core is not mysticism; it is the structure of alignment, subtraction, and reversal.",
        "primary_sources": [
            ref("Daodejing / Tao Te Ching", "Laozi tradition", "primary text", "老子的核心原典。", "The central primary text associated with Laozi."),
            ref("Mawangdui Laozi Manuscripts", "excavated text tradition", "manuscript tradition", "适合看到文本次序与版本差异。", "Useful for seeing early textual ordering and variation."),
            ref("Guodian Laozi Bamboo Slips", "excavated text tradition", "manuscript tradition", "帮助理解早期《老子》的形成与结构。", "Helps illuminate early formation and structure of the Laozi text."),
        ],
        "core_reading": [
            ref("Tao Te Ching", "translation by D. C. Lau", "scholarly translation", "稳健的英文入门版本之一。", "One of the more stable English entry points."),
            ref("Dao De Jing: A Philosophical Translation", "Roger T. Ames and David L. Hall", "interpretive translation", "适合把老子放进哲学语境而非鸡汤语境。", "Good for reading Laozi philosophically rather than proverbially."),
            ref("Daoism Explained", "Hans-Georg Moeller", "context book", "适合补足道家思想的大图景。", "Useful for broader Daoist context around the text."),
        ],
    },
    "lee_kuan_yew": {
        "intro_zh": "李光耀要先读回忆录和政策表达，再看外部评论。治理人物最怕只看评价，不看制度是怎么一步步落下来的。",
        "intro_en": "With Lee Kuan Yew, start with memoir and policy expression before outside interpretation. Governance figures are easiest to misread if you consume verdicts before institutions.",
        "primary_sources": [
            ref("The Singapore Story", "Lee Kuan Yew", "memoir", "理解其成长背景与早期政治形成。", "Useful for Lee's formative years and political development."),
            ref("From Third World to First", "Lee Kuan Yew", "memoir", "治理、制度和国家建设的核心一手材料。", "A core first-person record of governance, institution-building, and statecraft."),
            ref("Hard Truths to Keep Singapore Going", "Lee Kuan Yew", "interview volume", "看他如何在公开问答里阐明制度判断。", "Useful for Lee's institutional reasoning in direct interview form."),
        ],
        "core_reading": [
            ref("One Man's View of the World", "Lee Kuan Yew", "interviews and reflections", "适合看他对国际格局和国家竞争的判断。", "A good entry into Lee's view of geopolitics and state competition."),
            ref("Lee Kuan Yew: The Grand Master's Insights on China, the United States, and the World", "Graham Allison, Robert D. Blackwill, and Ali Wyne", "curated interviews", "帮助快速聚焦他对大国与秩序的判断。", "Useful for a focused read on Lee's geopolitical judgment."),
            ref("From Third World to First", "Lee Kuan Yew", "policy memoir", "若只读一本，优先这一本。", "If you read only one, start here."),
        ],
    },
    "zhongnanshan": {
        "intro_zh": "钟南山更适合通过论文、指南、公开通报和长访谈来读，而不是找一本包打天下的“人物书”。他的价值主要在于证据、临床和公共沟通三者如何连成一体。",
        "intro_en": "Zhong Nanshan is best read through papers, guidelines, public briefings, and long interviews rather than a single definitive book. His importance lies in how evidence, clinic, and public communication get tied together.",
        "primary_sources": [
            ref("Clinical Characteristics of Coronavirus Disease 2019 in China", "Wei-jie Guan et al. with Zhong Nanshan", "NEJM, 2020", "COVID-19 早期中国临床特征的关键论文。", "A key early paper on the clinical profile of COVID-19 in China."),
            ref("Comorbidity and its Impact on 1590 Patients with COVID-19 in China", "Wei-jie Guan et al. with Zhong Nanshan", "European Respiratory Journal, 2020", "看他如何把临床风险分层拉进公共讨论。", "Useful for seeing risk stratification pulled into public understanding."),
            ref("State Council and NHC Briefings Featuring Zhong Nanshan", "public briefings", "2020–2023 public record", "看他如何在不确定时公开讲话与风险沟通。", "Shows how he communicated evidence and risk under uncertainty."),
        ],
        "core_reading": [
            ref("Selected Respiratory and Public Health Interviews", "Zhong Nanshan", "long-form interviews", "适合补足论文之外的判断顺序与沟通方式。", "Good for his judgment sequence and communication style beyond the papers."),
            ref("Guidelines and Consensus Statements in Respiratory Medicine", "Zhong Nanshan and collaborating teams", "clinical guidelines", "适合看“证据如何变成行动”。", "Useful for seeing how evidence becomes practical action."),
            ref("COVID-19 and SARS Public Record in China", "public archive", "institutional record", "把他放回真实危机场景里去看。", "Helps place his work back inside the actual crisis setting."),
        ],
    },
    "peter_drucker": {
        "intro_zh": "德鲁克要先读原著，再读选编和管理学二手书。很多后来的管理术语都引用他，但真正的德鲁克远比“效率技巧”厚得多。",
        "intro_en": "Read Drucker's own books before the secondary management literature. Later management culture quotes him constantly, but the real Drucker is much deeper than productivity slogans.",
        "primary_sources": [
            ref("The Practice of Management", "Peter F. Drucker", "book", "管理学原典之一。", "One of the foundational management texts."),
            ref("The Effective Executive", "Peter F. Drucker", "book", "理解“贡献、重点和时间管理”的核心入口。", "The cleanest entry into contribution, focus, and executive effectiveness."),
            ref("Managing Oneself", "Peter F. Drucker", "essay", "最适合今天知识工作者的短文本之一。", "One of the best short texts for modern knowledge work."),
        ],
        "core_reading": [
            ref("Management: Tasks, Responsibilities, Practices", "Peter F. Drucker", "book", "更完整的体系性扩展。", "A fuller and more systematic expansion of his management worldview."),
            ref("Innovation and Entrepreneurship", "Peter F. Drucker", "book", "适合补足创新与组织增长的部分。", "Useful for innovation and organizational growth."),
            ref("Peter Drucker on Management", "Peter F. Drucker", "selected writings", "适合做快速主题复习。", "Good for faster thematic review."),
        ],
    },
    "peter_thiel": {
        "intro_zh": "蒂尔要先读《从 0 到 1》和课堂笔记，再回头看演讲与访谈。不要把他读成单纯“反共识表演者”。",
        "intro_en": "Start with Zero to One and the class notes, then use speeches and interviews. Do not reduce Thiel to a performer of contrarianism.",
        "primary_sources": [
            ref("Zero to One", "Peter Thiel with Blake Masters", "book", "理解蒂尔商业思想最核心的入口。", "The central entry point into Thiel's company-building worldview."),
            ref("CS183: Startup Notes", "Peter Thiel and Blake Masters", "lecture notes", "适合看他更展开、更课堂化的论证。", "Useful for the fuller classroom version of his arguments."),
            ref("Competition Is for Losers", "Peter Thiel", "essay/interview line", "“竞争不是目标”的一个高度浓缩版本。", "A concentrated statement of Thiel's critique of competition."),
        ],
        "core_reading": [
            ref("The Diversity Myth", "Peter Thiel and David Sacks", "book", "适合看其早期争议与思维风格源头。", "Useful for early intellectual style and controversy."),
            ref("Founders Fund Essays and Interviews", "Peter Thiel", "public archive", "补足《从 0 到 1》之外的投资与技术判断。", "Extends beyond Zero to One into investment and technology judgment."),
            ref("Zero to One", "Peter Thiel with Blake Masters", "book", "若只读一本到位，优先这一部。", "If you read only one, start here."),
        ],
    },
    "ray_dalio": {
        "intro_zh": "达利欧要先读《原则》和经济机器解释，再回头看债务周期研究。这样不会被术语淹没。",
        "intro_en": "Start with Principles and the economic-machine explanation, then move to debt-cycle research. That keeps the framework legible before the macro detail arrives.",
        "primary_sources": [
            ref("Principles: Life and Work", "Ray Dalio", "book", "达利欧世界观和组织方法的主入口。", "The main entry to Dalio's worldview and organizational method."),
            ref("How the Economic Machine Works", "Ray Dalio", "essay/video", "宏观判断的最简结构图。", "The simplest structural map of his macro thinking."),
            ref("Big Debt Crises", "Ray Dalio", "book", "债务周期与历史案例的原始教材。", "The major source for his debt-cycle framework and case studies."),
        ],
        "core_reading": [
            ref("Principles for Dealing with the Changing World Order", "Ray Dalio", "book", "更偏历史与国家竞争。", "More historical and geopolitical in scope."),
            ref("Bridgewater Daily Observations and Research Essays", "Bridgewater Associates", "research archive", "适合看原则如何落进日常分析。", "Shows how the principles get applied in day-to-day analysis."),
            ref("Big Debt Crises", "Ray Dalio", "book", "想真正理解其宏观框架，这本绕不开。", "Hard to avoid if you want the real macro framework."),
        ],
    },
    "bezos": {
        "intro_zh": "贝索斯最该先读股东信，再读《Invent and Wander》和公司史。因为真正的 Day 1 不是口号，而是机制。",
        "intro_en": "Read the shareholder letters first, then Invent and Wander and the best company histories. Day 1 is not a slogan; it is a system of mechanisms.",
        "primary_sources": [
            ref("Amazon Shareholder Letters", "Jeff Bezos", "1997–2020 archive", "理解客户至上、飞轮和长期主义的一手材料。", "The first-person record for customer obsession, flywheels, and long-term thinking."),
            ref("2016 Shareholder Letter", "Jeff Bezos", "letter", "Day 1 思想最常被引用的核心文本。", "The most-cited concentrated statement of Day 1 thinking."),
            ref("Invent and Wander", "Jeff Bezos", "writings and interviews", "适合直接读到贝索斯的公开表达和内部逻辑。", "Useful for Bezos in his own public voice across writings and interviews."),
        ],
        "core_reading": [
            ref("The Everything Store", "Brad Stone", "company history", "亚马逊早期与中期发展的经典外部叙事。", "The classic external account of Amazon's early and middle years."),
            ref("Amazon Unbound", "Brad Stone", "company history", "补足后期云、设备和帝国扩张阶段。", "Useful for the later cloud, devices, and empire-building period."),
            ref("Working Backwards", "Colin Bryar and Bill Carr", "inside account", "看亚马逊机制如何被制度化。", "Shows how Amazon's mechanisms were institutionalized."),
        ],
    },
    "satya_nadella": {
        "intro_zh": "纳德拉要先读《刷新》和文化转型原文，再看微软后续公开信和大会演讲。核心不是“温和”，而是“学习型组织如何落地”。",
        "intro_en": "Start with Hit Refresh and the culture-turnaround material, then move into later letters and keynotes. The point is not softness; it is how a learning organization gets built.",
        "primary_sources": [
            ref("Hit Refresh", "Satya Nadella", "book", "纳德拉自述的文化与战略转型主线。", "Nadella's own account of cultural and strategic renewal."),
            ref("2014 Email to Microsoft Employees", "Satya Nadella", "internal message made public", "理解其“新微软”文化转向的起点。", "The cleanest starting document for the early culture shift."),
            ref("Microsoft Build and Annual Letters", "Satya Nadella", "public archive", "看战略口径如何逐年变成平台与产品动作。", "Useful for seeing strategy translated into platform and product moves."),
        ],
        "core_reading": [
            ref("Hit Refresh", "Satya Nadella", "book", "如果只读一本，先读它。", "If you read only one, start here."),
            ref("Microsoft Transformation Interviews", "Satya Nadella", "long-form interviews", "适合补足书里较少展开的执行细节。", "Good for execution detail beyond the book."),
            ref("Platform and Cloud Keynotes", "Satya Nadella", "public talks", "适合理解文化与平台判断如何绑定。", "Useful for the link between culture and platform strategy."),
        ],
    },
    "andrew_ng": {
        "intro_zh": "吴恩达最适合通过课程讲义、短文和应用型演讲来读。不要先追热点概念，要先看他如何把 AI 收敛成可落地的问题。",
        "intro_en": "Andrew Ng is best read through courses, short essays, and application talks. Do not start with hype categories before seeing how he narrows AI into deployable problems.",
        "primary_sources": [
            ref("Machine Learning Yearning", "Andrew Ng", "book draft", "吴恩达最像“产品化 AI 方法论”的文本。", "His closest thing to an applied operating manual for machine learning."),
            ref("AI Is the New Electricity", "Andrew Ng", "talk / public framing", "理解其普及 AI 的核心比喻。", "A concentrated statement of his practical AI worldview."),
            ref("DeepLearning.AI and Stanford Course Materials", "Andrew Ng", "course archive", "适合看他如何把复杂主题讲成可学习结构。", "Useful for how he turns complex topics into learnable operating structure."),
        ],
        "core_reading": [
            ref("Data-Centric AI Talks and Notes", "Andrew Ng", "public talks", "补足他近年把“模型崇拜”拉回数据工作的部分。", "Useful for his newer emphasis on data-centric work over model worship."),
            ref("Applied AI Interviews", "Andrew Ng", "long-form interviews", "适合看他如何判断真实落地场景。", "Good for how he sizes real deployment opportunities."),
            ref("Machine Learning Yearning", "Andrew Ng", "book draft", "想上手应用 AI，这本仍然非常值。", "Still one of the most useful texts for applying AI in practice."),
        ],
    },
    "li_feifei": {
        "intro_zh": "李飞飞先读自传与 ImageNet 论文，再读她关于 human-centered AI 的公开表达。她不是只讲技术，也不是只讲伦理，而是把两者放在同一张桌子上。",
        "intro_en": "Start with the memoir and the ImageNet paper, then move into her human-centered AI talks. Fei-Fei Li is not only about technical progress or only about ethics; she forces both onto the same table.",
        "primary_sources": [
            ref("The Worlds I See", "Fei-Fei Li", "memoir", "最适合进入李飞飞科学路径和价值框架的一本书。", "One of the best entry points into both her scientific path and moral frame."),
            ref("ImageNet: A Large-Scale Hierarchical Image Database", "Jia Deng et al. with Fei-Fei Li", "CVPR 2009", "理解现代计算机视觉数据基础设施的关键论文。", "The key paper behind the data infrastructure of modern computer vision."),
            ref("Human-Centered AI Talks and HAI Lectures", "Fei-Fei Li", "public talks", "看她如何把技术进步与社会后果一起讨论。", "Useful for how she puts technical progress and social consequence together."),
        ],
        "core_reading": [
            ref("The Worlds I See", "Fei-Fei Li", "memoir", "如果你只读一本到位，这本兼具科学史与人物感。", "If you read only one, this balances science history with personal voice."),
            ref("Stanford HAI Public Essays", "Fei-Fei Li", "essay archive", "适合补足其 human-centered AI 公共论述。", "Good for her public articulation of human-centered AI."),
            ref("ImageNet Retrospectives and Interviews", "Fei-Fei Li", "interviews", "帮助理解数据集、平台和学科转折。", "Useful for context around datasets, platforms, and discipline shifts."),
        ],
    },
    "daniel_kahneman": {
        "intro_zh": "卡尼曼要先读原始论文，再读《思考，快与慢》和《噪声》。如果只读畅销书，很容易变成偏误词典，而不是判断训练。",
        "intro_en": "Read the classic papers before Thinking, Fast and Slow and Noise. Otherwise Kahneman gets flattened into a bias glossary instead of a discipline of judgment.",
        "primary_sources": [
            ref("Judgment under Uncertainty: Heuristics and Biases", "Amos Tversky and Daniel Kahneman", "Science, 1974", "启发式与偏误研究的起点论文。", "A foundational paper for the heuristics-and-biases program."),
            ref("Prospect Theory: An Analysis of Decision under Risk", "Daniel Kahneman and Amos Tversky", "Econometrica, 1979", "前景理论的原始文本。", "The original text of prospect theory."),
            ref("Thinking, Fast and Slow", "Daniel Kahneman", "book", "把几十年研究压成公共语言的一本书。", "The public-facing synthesis of decades of work."),
        ],
        "core_reading": [
            ref("Noise", "Daniel Kahneman, Olivier Sibony, and Cass R. Sunstein", "book", "适合补足“偏误之外”的判断波动问题。", "Useful for judgment variability beyond classic bias language."),
            ref("Maps of Bounded Rationality", "Daniel Kahneman", "Nobel lecture", "回到更学术、更浓缩的自我总结。", "A tighter academic self-summary of his program."),
            ref("Attention and Effort", "Daniel Kahneman", "book", "适合补足他更早期的认知研究背景。", "Useful for early cognitive background to later judgment work."),
        ],
    },
    "aristotle": {
        "intro_zh": "亚里士多德不能只读摘句，要读伦理学、政治学和修辞学的组合。这样才能看到他如何把“目的、德性、实践智慧”连成一体。",
        "intro_en": "Do not read Aristotle as a book of isolated sayings. Read ethics, politics, and rhetoric together to see how purpose, virtue, and practical wisdom form one system.",
        "primary_sources": [
            ref("Nicomachean Ethics", "Aristotle", "primary text", "德性、幸福与实践智慧的主文本。", "The central text for virtue, flourishing, and practical wisdom."),
            ref("Politics", "Aristotle", "primary text", "把伦理人与城邦秩序放到一起读。", "Useful for placing ethical life inside political order."),
            ref("Rhetoric", "Aristotle", "primary text", "看判断、情感与说服如何成为实践的一部分。", "Shows how judgment, emotion, and persuasion enter practical life."),
        ],
        "core_reading": [
            ref("Metaphysics", "Aristotle", "primary-adjacent text", "适合补足其分类与存在论背景。", "Useful for the broader background of classification and being."),
            ref("Aristotle: A Very Short Introduction", "Jonathan Barnes", "guide", "适合做结构化入门。", "A strong compact orientation."),
            ref("Nicomachean Ethics", "scholarly annotated edition", "study edition", "要真正读亚里士多德，译注版本很重要。", "Annotated editions matter a great deal for a serious read."),
        ],
    },
    "socrates": {
        "intro_zh": "苏格拉底没有留下自己写的书，所以必须通过柏拉图和色诺芬进入。重点不是“金句”，而是他如何一步步拆掉伪知识。",
        "intro_en": "Socrates left no writings of his own, so the entry point is Plato and Xenophon. The point is not the famous lines but the step-by-step dismantling of false knowledge.",
        "primary_sources": [
            ref("Apology", "Plato", "dialogue", "苏格拉底最核心的自我辩护文本。", "The core text for Socrates' public defense and moral posture."),
            ref("Crito", "Plato", "dialogue", "适合理解苏格拉底对法、义务与灵魂的判断。", "Useful for law, obligation, and the care of the soul."),
            ref("Memorabilia", "Xenophon", "recollection", "用另一位弟子的视角补足苏格拉底形象。", "A second vantage point from another student and witness."),
        ],
        "core_reading": [
            ref("Plato: Five Dialogues", "Plato", "collected dialogues", "非常适合作为苏格拉底入门。", "A strong practical entrance to Socratic dialogue."),
            ref("Socrates: Ironist and Moral Philosopher", "Gregory Vlastos", "interpretive book", "学术上非常重要的现代阐释。", "A major modern interpretation."),
            ref("The Trial and Death of Socrates", "Plato translation volume", "study edition", "适合把《申辩》《克里托》放在一起读。", "A useful grouped edition for reading the key trial texts together."),
        ],
    },
    "wang_yangming": {
        "intro_zh": "王阳明要先读《传习录》和《大学问》，再读现代研究。核心不是口号式“知行合一”，而是他如何处理良知、自欺与实践。",
        "intro_en": "Start with Instructions for Practical Living and Inquiry on the Great Learning, then add modern studies. The core is not the slogan of unity of knowledge and action but how Wang treats conscience, self-deception, and practice.",
        "primary_sources": [
            ref("Instructions for Practical Living (传习录)", "Wang Yangming", "primary text", "理解王阳明的首要文本。", "The indispensable primary text for Wang Yangming."),
            ref("Inquiry on the Great Learning (大学问)", "Wang Yangming", "essay", "适合看其修身与秩序的连通方式。", "Useful for the connection between self-cultivation and order."),
            ref("Collected Writings of Wang Yangming", "Wang Yangming", "collected works", "补足更完整的文献面。", "Useful for a wider documentary picture of the corpus."),
        ],
        "core_reading": [
            ref("Instructions for Practical Living and Other Neo-Confucian Writings", "translated selections", "study edition", "英文世界读王阳明的重要入口。", "A major English-language entrance to Wang's thought."),
            ref("The Philosophy of Wang Yangming", "modern study", "interpretive book", "适合快速搭建概念图。", "Useful for building a conceptual map quickly."),
            ref("Wang Yang-Ming: Idealist Philosopher of Sixteenth-Century China", "Frederick Goodrich Henke", "study", "较早但仍值得参考的研究。", "An older but still useful study."),
        ],
    },
    "linus_torvalds": {
        "intro_zh": "Linus 先读原始邮件、发布说明和自传，再看开源文化史。因为真正的 Linus 不在励志故事里，而在工程反馈循环里。",
        "intro_en": "Read the original emails, release notes, and memoir before the open-source histories. The real Linus lives in the engineering feedback loop, not the inspiration story.",
        "primary_sources": [
            ref("1991 Minix Announcement", "Linus Torvalds", "mailing list post", "Linux 起点文本。", "The starting text of the Linux story."),
            ref("Linux Kernel Mailing List Posts and Release Notes", "Linus Torvalds", "public archive", "看他如何在真实工程讨论里做判断。", "The best place to see Linus making decisions in live engineering context."),
            ref("Git Mailing List Design Discussions", "Linus Torvalds", "public archive", "适合理解其工具观与系统观。", "Useful for his view of tools, architecture, and workflow."),
        ],
        "core_reading": [
            ref("Just for Fun", "Linus Torvalds with David Diamond", "memoir", "Linus 自己的生平与开源形成史。", "Linus's own memoir and the story of open-source formation."),
            ref("Rebel Code", "Glyn Moody", "technology history", "补足开源生态与历史背景。", "Adds ecosystem and historical context around open source."),
            ref("Linux Kernel Documentation", "Linux community", "engineering archive", "从文档层面理解其工程哲学。", "Useful for the engineering philosophy embodied in practice."),
        ],
    },
    "tim_berners_lee": {
        "intro_zh": "Tim 先读 1989 提案、Web 原始文档和 W3C 公开文本，再读《编织万维网》。这样能避免把他读成“发明者故事”，而忽略开放标准的制度选择。",
        "intro_en": "Read the 1989 proposal, early web documents, and W3C texts before or alongside Weaving the Web. That prevents turning Berners-Lee into a simple inventor story while missing the institutional choice of openness.",
        "primary_sources": [
            ref("Information Management: A Proposal", "Tim Berners-Lee", "CERN, 1989/1990", "万维网最初的提案文本。", "The original proposal for the World Wide Web."),
            ref("Weaving the Web", "Tim Berners-Lee with Mark Fischetti", "book", "Tim 对 Web 起源和原则的自述。", "Berners-Lee's own narrative of the web's origin and principles."),
            ref("Long Live the Web", "Tim Berners-Lee", "essay", "开放网络价值观的公开申明。", "A direct public defense of an open web."),
        ],
        "core_reading": [
            ref("W3C Design Issues and Architecture Notes", "Tim Berners-Lee / W3C", "public archive", "帮助理解开放标准和互操作性的底层哲学。", "Useful for the philosophy of standards and interoperability."),
            ref("WorldWideWeb and CERN Web Archives", "CERN / W3C", "historical archive", "回到早期网页与说明文档最有帮助。", "Very useful for returning to the earliest web documents themselves."),
            ref("Weaving the Web", "Tim Berners-Lee with Mark Fischetti", "book", "若想从人和制度一起读起，这本最好。", "A strong single volume if you want both the person and the institutional vision."),
        ],
    },
    "musk": {
        "intro_zh": "马斯克要同时读 master plan、硬科技发布和权威传记。只看新闻会失真，必须回到技术目标、成本曲线和迭代节奏。",
        "intro_en": "Read the master plans, the hard-tech presentations, and the strongest biographies together. News coverage alone distorts him; the real story sits in technical goals, cost curves, and iteration speed.",
        "primary_sources": [
            ref("The Secret Tesla Motors Master Plan (just between you and me)", "Elon Musk", "2006 post", "早期路线图文本。", "The early roadmap statement."),
            ref("Master Plan, Part Deux", "Elon Musk", "2016 post", "从电动车到更大系统布局的延伸。", "The extension from electric cars into a broader systems vision."),
            ref("Tesla, SpaceX, and xAI Product and Strategy Presentations", "Elon Musk", "public talks", "适合看野心如何落到工程与产线。", "Useful for seeing how ambition gets translated into engineering and production."),
        ],
        "core_reading": [
            ref("Elon Musk", "Walter Isaacson", "biography", "最新的大部头传记。", "The major recent biography."),
            ref("Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future", "Ashlee Vance", "biography", "早期到中期阶段非常重要。", "Important for the earlier and middle periods."),
            ref("Liftoff", "Eric Berger", "company history", "如果想理解 SpaceX 的工程文化，很值得读。", "Especially useful for SpaceX's engineering culture."),
        ],
    },
    "caodewang": {
        "intro_zh": "曹德旺应先读《心若菩提》和公开演讲，再看工厂与产业案例。重点是制造业判断、产品纪律和企业责任，而不是鸡汤式创业故事。",
        "intro_en": "Start with Mind Like a Bodhi Tree and his public talks, then pair them with factory and industry cases. The real value is manufacturing judgment, product discipline, and founder responsibility.",
        "primary_sources": [
            ref("心若菩提", "曹德旺", "自述", "理解曹德旺人生观和制造观的主入口。", "The main entrance to Cao Dewang's worldview and manufacturing philosophy."),
            ref("曹德旺公开演讲与长访谈", "曹德旺", "public archive", "最适合看他真实表达中的判断顺序。", "The best place to hear his unsmoothed judgment sequence."),
            ref("American Factory", "documentary record", "film / factory case", "把福耀美国工厂放进真实组织冲突里观察。", "Useful for seeing Fuyao in a live cross-cultural factory setting."),
        ],
        "core_reading": [
            ref("制造业与企业经营访谈汇编", "Cao Dewang interview collections", "public materials", "补足其对成本、组织和全球制造的看法。", "Adds his thinking on cost, organization, and global manufacturing."),
            ref("American Factory", "film and related reporting", "case material", "如果要看制造业现实冲突，这个案例很直观。", "A vivid case if you want to see manufacturing friction in practice."),
            ref("心若菩提", "曹德旺", "memoir", "若只读一本，仍然从这本开始。", "If you read only one, still start here."),
        ],
    },
    "zaha_hadid": {
        "intro_zh": "扎哈要先读作品集、事务所项目说明和展览图录，再读二手设计史。她最重要的不是“酷”，而是空间逻辑如何被做成现实建筑。",
        "intro_en": "Start with project books, office statements, and exhibition catalogues before design history commentary. The real question is not whether Zaha is 'cool' but how spatial logic becomes buildable architecture.",
        "primary_sources": [
            ref("Zaha Hadid: Complete Works", "Zaha Hadid", "project compendium", "最适合系统看作品、图纸和项目说明。", "A strong systematic view of projects, drawings, and design statements."),
            ref("Project Statements from Zaha Hadid Architects", "Zaha Hadid Architects", "office archive", "适合理解每个项目的空间逻辑与叙述。", "Useful for the stated spatial logic behind individual projects."),
            ref("Major Exhibition Catalogues", "Zaha Hadid", "exhibition materials", "看她如何把建筑语言先在图像和展览层面展开。", "Shows how the architectural language is articulated through exhibition material."),
        ],
        "core_reading": [
            ref("Zaha Hadid", "Philip Jodidio", "monograph", "经典入门图录之一。", "A classic introductory monograph."),
            ref("Zaha Hadid and Suprematism", "edited design studies", "study volume", "适合理解其形式语言的艺术谱系。", "Useful for the artistic genealogy of her formal language."),
            ref("Complete Works", "revised editions", "study reference", "想真正进入她的项目世界，这一类资料最值。", "If you want to really enter her project world, these are among the most valuable materials."),
        ],
    },
}
